# Generated by Django 5.1.4 on 2024-12-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
